blank_issues_enabled: true
contact_links:
  - name: ğŸ’ Support
    url: https://chat.studiocms.dev
    about: 'This issue tracker is not for support questions. Join us on Discord for assistance!'
  - name: ğŸ‘¾ Chat
    url: https://chat.studiocms.dev
    about: Our Discord server is active, come join us!
